name: daily

on:
  schedule:
    - cron:  '30 18-23 * * *'
jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: npm install
    - name: Scrap
      run: npm start 
    - name: Commit files
      run: |
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git add .
       git diff-index --quiet HEAD || git commit -m "Update json" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
